Sprint 7 solution in file manager
SergeiMish/java-kanban pull request #2
Opened 2024-09-29 15:14 UTC by SergeiMish

2024-10-01 06:21 UTC, NikolaiDem requested changes

2024-10-01 06:21 UTC, NikolaiDem commented on test/manager/FileBackedTaskManagerTest.java
> +    void loadMultipleTasks() {
А вот такой тест не работает:

      File tempFile = File.createTempFile("loadTasks", null);
            Files.write(tempFile.toPath(), List.of(
                    "Task{Название: 'Task 1', детали: 'Detail 1', id :3, статус: NEW}",
                    "Task{Название: 'Task 2', детали: 'Detail 2', id :5, статус: IN_PROGRESS}",
                    "Epic{Название: 'Epic 1', детали: 'Epic Detail', id :7, статус: NEW}",
                    "SubTask{Название: 'SubTask 1', детали: 'SubTask Detail', id :4, статус: NEW, epicId: 3}"
            ));

            FileBackedTaskManager manager = FileBackedTaskManager.loadFromFile(tempFile);

            var listTasks = manager.getListTasks();
            assertEquals(2, listTasks.size(), "Должно быть загружено 2 задачи");
            assertEquals(3, listTasks.getFirst().getId());

2024-10-01 06:21 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +    public Map<Integer, Task> getIdToTask() {
Эти методы лишние

2024-10-01 06:21 UTC, NikolaiDem commented on src/manager/FileBackedTaskManager.java
> +            for (Map.Entry<Integer, Task> entry : getIdToTask().entrySet()) {
Почему не подходит getListTasks() ?

2024-10-01 11:35 UTC, SergeiMish commented on src/manager/FileBackedTaskManager.java
> +            for (Map.Entry<Integer, Task> entry : getIdToTask().entrySet()) {
Исправил на  getListTasks(), почему то в голову пришло создать getIdToTask, попробовал в реализации, и оно сразу заработало, дальше уже в другие задачи ушел.

2024-10-01 11:35 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
> +    public Map<Integer, Task> getIdToTask() {
Убрал

2024-10-01 11:37 UTC, SergeiMish commented on test/manager/FileBackedTaskManagerTest.java
> +    void loadMultipleTasks() {
Добавил этот тест, теперь работает как надо, проблема была в реализации счетчика Id. По Эпикам так же. Хотел так же попросить дать комментарий по реализации через регулярное выражение, и вообще в целом по "коду". Может есть критичные моменты на что стоит обратить внимание или рекомендации, буду признателен.

2024-10-01 22:10 UTC, NikolaiDem requested changes

2024-10-01 22:10 UTC, NikolaiDem commented on src/manager/FileBackedTaskManager.java
> +            throw new RuntimeException("Ошибка при чтении файла", e);
RuntimeException лучше не бросать. 
Лучше создать свое непроверяемое исключение, наследуемое от RE. Чем более узкоспециализированное исключение, тем легче и быстрее найти и выяснить причину ошибки

2024-10-01 22:10 UTC, NikolaiDem commented on src/manager/FileBackedTaskManager.java
> +        return newTask;
Нужно вернуть сохраненную таску, а не переданную.
Аналогично для эпиков и сабтасок и методов обновления

2024-10-01 22:10 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +        if (newTask.getId() == 0) {
Ведь 0 тоже может валидным идентификатором, поэтому вместо такой проверки можно создать поле initialized в таске, которое менять на true в методе setId(...). И проверять по нему

2024-10-01 22:11 UTC, NikolaiDem commented on test/manager/FileBackedTaskManagerTest.java
> +    void loadMultipleTasks() {
По данному ПР все хорошо.
Только вмержи перед ним пр по 6 спринту

2024-10-02 04:52 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
> +        if (newTask.getId() == 0) {
Исправил.

2024-10-02 04:53 UTC, SergeiMish commented on src/manager/FileBackedTaskManager.java
> +        return newTask;
Исправил.

2024-10-02 04:53 UTC, SergeiMish commented on src/manager/FileBackedTaskManager.java
> +            throw new RuntimeException("Ошибка при чтении файла", e);
исправил

2024-10-02 04:53 UTC, SergeiMish commented on test/manager/FileBackedTaskManagerTest.java
> +    void loadMultipleTasks() {
сделано

2024-10-02 08:48 UTC, NikolaiDem approved these changes

2024-10-02 09:01 UTC, merged