Sprint 8 solution time and duration
SergeiMish/java-kanban pull request #3
Opened 2024-10-11 14:29 UTC by SergeiMish

2024-10-11 22:36 UTC, NikolaiDem requested changes

2024-10-11 22:36 UTC, NikolaiDem commented on src/interfaces/TaskManager.java
> +    void updateEpicStatus(int id);
Этот метод является служебным, выносить в интерфейс не нужно

2024-10-11 22:36 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +    private void updatePrioritizedTasks() {
Не нужно обновлять весь список отсортированных тасок при каждом изменении. Необходимо лишь добавлять/удалять из prioritizedTasks при изменении таски.

2024-10-11 22:36 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +    public boolean isOverlapping(Task task1, Task task2) {
priavate

2024-10-11 22:36 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +        if (idToEpic.isEmpty()) {
Можно проще:

Epic epic = idToEpic.get(epicId);
        if (epic == null) {
            return null;
        }
        return epic.getListSubTask()
                .stream()
                .map(idToSubTask::get)
                .map(Task::getEndTime)
                .filter(Objects::nonNull)
                .max(Comparator.naturalOrder())
                .orElse(null);

2024-10-11 22:36 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +    public LocalDateTime getEndTimeEpic(int epicId) {
private

2024-10-11 22:36 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
>      public void updateEpicStatus(int epicId) {
private

2024-10-11 22:36 UTC, NikolaiDem commented on src/tasks/Epic.java
>  public class Epic extends Task {
Не реализован пункт ТЗ:
А вот с классом Epic нужно поработать дополнительно. Продолжительность эпика — сумма продолжительностей всех его подзадач. Время начала — дата старта самой ранней подзадачи, а время завершения — время окончания самой поздней из задач. Новые поля duration и startTime этого класса будут расчётные — аналогично полю «статус». Для реализации getEndTime() удобно добавить поле endTime в Epic и рассчитать его вместе с другими полями.

2024-10-12 05:29 UTC, SergeiMish commented on src/tasks/Epic.java
>  public class Epic extends Task {
Реализовано

2024-10-12 05:30 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
>      public void updateEpicStatus(int epicId) {
При смене на private весь код попадает по изменение. Значит придется делать на этот метод gettre что бы вызвать его в другом месте?

2024-10-12 05:30 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
> +    public LocalDateTime getEndTimeEpic(int epicId) {
готово

2024-10-12 05:30 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
> +        if (idToEpic.isEmpty()) {
Исправил, круто

2024-10-12 05:30 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
> +    public boolean isOverlapping(Task task1, Task task2) {
готово

2024-10-12 05:30 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
> +    private void updatePrioritizedTasks() {
Убрал лишнее

2024-10-12 05:30 UTC, SergeiMish commented on src/interfaces/TaskManager.java
> +    void updateEpicStatus(int id);
Убрал из интерфейса

2024-10-13 12:57 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
>      public void updateEpicStatus(int epicId) {
Что попадает под изменение?

2024-10-13 12:57 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +    private void updatePrioritizedTasks() {
Не исправлено

2024-10-13 12:59 UTC, NikolaiDem commented on src/tasks/Epic.java
> +    private void recalculateTimes(Task subTask, boolean isAdding) {
Лучше разделить на 2 метода.
Аргумент boolean является code smells

2024-10-13 15:33 UTC, NikolaiDem requested changes

2024-10-13 15:33 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +            updatePrioritizedTasks();
Для чего?

2024-10-13 15:33 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +        if (canAddTask(newSubTask)) {
Лучше так
if (!canAddTask(newSubTask)) {
            throw new IllegalArgumentException("Подзадачи пересекаются по времени");
        }

2024-10-13 15:33 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
>      public SubTask createSubTask(SubTask newSubTask) {
Такой метод читается легче:

    public SubTask createSubTask(SubTask newSubTask) {
        if (!canAddTask(newSubTask)) {
            throw new IllegalArgumentException("Подзадачи пересекаются по времени");
        }
        int epicId = newSubTask.getEpicId();
        Epic epic = idToEpic.get(epicId);
        if (epic == null) {
            throw new IllegalArgumentException("Invalid epicId " + epicId);
        }
        if (!newSubTask.isInitialized()) {
            int newId = id++;
            newSubTask.setId(newId);
            epic.addSubTask(newSubTask);
        }
        idToSubTask.put(newSubTask.getId(), newSubTask);
        updateEpicStatus(epic.getId());
        return newSubTask;
    }

2024-10-13 15:33 UTC, NikolaiDem commented on src/tasks/Epic.java
> +            duration = duration.minus(subTask.getDuration());
А при удалении не нужно startTime и endTime пересчитывать ?

2024-10-14 08:03 UTC, SergeiMish commented on src/tasks/Epic.java
> +            duration = duration.minus(subTask.getDuration());
Исправил

2024-10-14 08:03 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
>      public SubTask createSubTask(SubTask newSubTask) {
Исправил, спасибо

2024-10-14 08:04 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
> +            updatePrioritizedTasks();
Убрал

2024-10-14 08:04 UTC, SergeiMish commented on src/tasks/Epic.java
> +    private void recalculateTimes(Task subTask, boolean isAdding) {
Разделил, заодно почитал про code smells

2024-10-14 08:04 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
>      public void updateEpicStatus(int epicId) {
Разобрался, поменял, все работает

2024-10-14 08:05 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
> +    private void updatePrioritizedTasks() {
Убрал этот метод и добавил 2 других addTaskToPrioritized(Task task) и  removeTaskFromPrioritized(Task task)

2024-10-14 18:55 UTC, NikolaiDem requested changes

2024-10-14 18:55 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
>      @Override
При обновлении таски у нее может поменяться время, поэтому нужно сначала удалить старую, а потом добавить новую.
Аналогично для сабтасок

2024-10-14 18:55 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +        getEndTimeEpic(newId);
А зачем здесь вызывается метод getEndTimeEpic(...)?

2024-10-14 18:55 UTC, NikolaiDem commented on src/tasks/Epic.java
> +    public void removeSubTask(Task subTask, List<Task> allSubTasks) {
Лучше пересчитывать все временные параметры эпика в менеджере, чтобы не передавать все таски в эпик

2024-10-14 18:55 UTC, NikolaiDem commented on src/tasks/Epic.java
> +                LocalDateTime subTaskEndTime = subTask.getStartTime().plus(subTask.getDuration());
subTask.getEndTime()?

2024-10-15 11:47 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
> +        getEndTimeEpic(newId);
Убрал

2024-10-15 11:47 UTC, SergeiMish commented on src/tasks/Epic.java
> +    public void removeSubTask(Task subTask, List<Task> allSubTasks) {
Перенес

2024-10-15 11:48 UTC, SergeiMish commented on src/tasks/Epic.java
> +                LocalDateTime subTaskEndTime = subTask.getStartTime().plus(subTask.getDuration());
Добавил (и перенес в менеджер)

2024-10-15 11:48 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
>      @Override
Сделано

2024-10-15 17:00 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
>      @Override
А если у обновляющей таски время будет такое, что возникнет пересечение с существующими задачами, нужно ли выполнять обновление?

2024-10-15 17:56 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
>      @Override
Нет, если обновляемая задача имеет время, которое пересекается с существующими задачами, обновление не должно выполняться. Поменял для задач и подзадач

2024-10-15 21:02 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +        addTaskToPrioritized(newEpic);
Эпики не нужно добавлять в список приоритетных задач

2024-10-16 04:39 UTC, SergeiMish commented on src/manager/InMemoryTaskManager.java
> +        addTaskToPrioritized(newEpic);
Точно, убрал метод добавления при создании и removeTaskFromPrioritized(epic); при удалении.

2024-10-16 09:23 UTC, NikolaiDem approved these changes

2024-10-16 14:22 UTC, merged