Sprint 9 solution http api
SergeiMish/java-kanban pull request #4
Opened 2024-10-24 18:02 UTC by SergeiMish

2024-10-26 00:08 UTC, NikolaiDem requested changes

2024-10-26 00:08 UTC, NikolaiDem commented on src/server/EpicHandler.java
> +    private final InMemoryTaskManager manager;
private final TaskManager manager;

2024-10-26 00:08 UTC, NikolaiDem commented on src/server/EpicHandler.java
> +    public void handle(HttpExchange exchange) throws IOException {
throws IOException не нужен

2024-10-26 00:08 UTC, NikolaiDem commented on src/server/EpicHandler.java
> +                        manager.getListEpic();
Для чего?

2024-10-26 00:08 UTC, NikolaiDem commented on src/server/EpicHandler.java
> +                        if (id != -1) {
А если в pathId будет "-1", это тоже невалидный id? А если "-2"?
Исправить для всех таких проверок

2024-10-26 00:08 UTC, NikolaiDem commented on src/server/EpicHandler.java
> +                        InputStreamReader isr = new InputStreamReader(exchange.getRequestBody(), StandardCharsets.UTF_8);
Все IOS лучше открывать с помощью try-with-resources

2024-10-26 00:08 UTC, NikolaiDem commented on src/server/EpicHandler.java
> +                        if (i == null) {
getId() возвращает примитив, эта проверка всегда false

2024-10-26 00:08 UTC, NikolaiDem commented on src/server/EpicHandler.java
> +            e.printStackTrace();
e.printStackTrace() - code smells, лучше или логировать или бросить исключение

2024-10-26 00:08 UTC, NikolaiDem commented on src/server/EpicHandler.java
> +public class EpicHandler extends BaseHttpHandler implements HttpHandler {
Все комментарии к EpicHandler справедливы и для остальных хэндлеров

2024-10-26 00:08 UTC, NikolaiDem commented on src/server/SubTaskHandler.java
> +                            if (manager.canAddTask(subTask)) {
Метод не нужен

2024-10-26 00:08 UTC, NikolaiDem commented on src/server/SubTaskHandler.java
> +                                manager.createSubTask(subTask);
Лучше обработать исключение о пересечении таски с существующими и отправить ответ 406

2024-10-26 00:08 UTC, NikolaiDem commented on src/server/adapter/LocalDateAdapter.java
> +public class LocalDateAdapter extends TypeAdapter<LocalDate> {
А как адаптер обрабатывает null значения?

2024-10-26 00:08 UTC, NikolaiDem commented on src/server/adapter/LocalTimeAdapter.java
> +public class LocalTimeAdapter extends TypeAdapter<LocalTime> {
А как адаптер обрабатывает null значения?

2024-10-26 10:52 UTC, SergeiMish commented on src/server/EpicHandler.java
> +    private final InMemoryTaskManager manager;
Готово

2024-10-26 10:52 UTC, SergeiMish commented on src/server/EpicHandler.java
> +    public void handle(HttpExchange exchange) throws IOException {
Убрал

2024-10-26 10:52 UTC, SergeiMish commented on src/server/EpicHandler.java
> +                        manager.getListEpic();
Убрал, задвоился

2024-10-26 10:52 UTC, SergeiMish commented on src/server/EpicHandler.java
> +                        if (id != -1) {
Исправил логику на проверку > 0

2024-10-26 10:53 UTC, SergeiMish commented on src/server/EpicHandler.java
> +                        InputStreamReader isr = new InputStreamReader(exchange.getRequestBody(), StandardCharsets.UTF_8);
Готово

2024-10-26 10:53 UTC, SergeiMish commented on src/server/EpicHandler.java
> +public class EpicHandler extends BaseHttpHandler implements HttpHandler {
Исправлено у остальных

2024-10-26 10:53 UTC, SergeiMish commented on src/server/SubTaskHandler.java
> +                            if (manager.canAddTask(subTask)) {
Убрал

2024-10-26 10:53 UTC, SergeiMish commented on src/server/SubTaskHandler.java
> +                                manager.createSubTask(subTask);
Сделал ответ кода 406

2024-10-26 10:53 UTC, SergeiMish commented on src/server/adapter/LocalDateAdapter.java
> +public class LocalDateAdapter extends TypeAdapter<LocalDate> {
Добавил

2024-10-26 10:54 UTC, SergeiMish commented on src/server/adapter/LocalTimeAdapter.java
> +public class LocalTimeAdapter extends TypeAdapter<LocalTime> {
Добавил

2024-10-27 17:37 UTC, NikolaiDem requested changes

2024-10-27 17:37 UTC, NikolaiDem commented on test/server/HttpTaskServerTest.java
> +    void taskAdd() throws IOException, InterruptedException {
Как так получается, задачу добавили, а в списке задач ее нет?

    @Test
    void taskAdd() throws IOException, InterruptedException {

        Task task1 = new Task("Имя", "детали", date, time, 30, Status.NEW);

        String taskJson = gson.toJson(task1);

        HttpClient client = HttpClient.newHttpClient();
        URI url = URI.create("http://localhost:8080/tasks");
        HttpRequest request = HttpRequest.newBuilder().uri(url).POST(HttpRequest.BodyPublishers.ofString(taskJson)).build();
        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
        assertEquals(200, response.statusCode());
        
        HttpRequest getTasks = HttpRequest.newBuilder().uri(url).GET().build();
        String body = client.send(getTasks, HttpResponse.BodyHandlers.ofString()).body();
        Gson gson = getGson();
        List<Task> tasks = gson.fromJson(body, new TypeToken<>() {
        });
        assertFalse(tasks.isEmpty());
    }

Аналогично для сабтасок

2024-10-27 17:56 UTC, SergeiMish commented on test/server/HttpTaskServerTest.java
> +    void taskAdd() throws IOException, InterruptedException {
Поменял немного тесты, добавил проверку на попадание в список.

2024-10-27 19:21 UTC, SergeiMish commented on src/server/EpicHandler.java
> +                        if (i == null) {
Поменял

2024-10-27 19:22 UTC, SergeiMish commented on src/server/EpicHandler.java
> +            e.printStackTrace();
Сделал выброс исключения. Логировать не стал, еще не разбирался в этой теме.

2024-10-28 20:12 UTC, NikolaiDem approved these changes

2024-10-29 03:19 UTC, merged